node {
  stage 'build app'
  openshiftBuild(namespace: 'demo', buildConfig: 'welcome', showBuildLogs: 'true')
  stage 'execute image scan'
    openshift.withCluster() {
    echo "Hello from mycluster's default project: ${openshift.project()}"
    }  
  stage 'deploy app'
  openshiftDeploy(namespace: 'demo', deploymentConfig: 'welcome')
}
